# Generated by Django 2.2 on 2019-04-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Profile',
        ),
    ]
